wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1674399445.361279
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 5
batch_size:
  desc: null
  value: 16
choice_data:
  desc: null
  value:
  - 1-1.
  - 1-2.
  - 1-7.
  - 2-4.
  - 2-6.
  - 2-7.
  - 2-9.
  - 3-1.
  - 3-3.
  - 3-4.
  - 3-6.
  - 3-7.
  - 3-9.
criterion:
  desc: null
  value: MSE
data_path:
  desc: null
  value: ./TimeSeries-Anomaly-Detection-Dataset/data/
dataset:
  desc: null
  value: SMD
device:
  desc: null
  value: 0
epoch:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.001
mode:
  desc: null
  value: all
model:
  desc: null
  value: AE
optimizer:
  desc: null
  value: SGD
pred_len:
  desc: null
  value: 1
save_path:
  desc: null
  value: ./model_save/
scheduler:
  desc: null
  value: null
seed:
  desc: null
  value: 1004
seq_len:
  desc: null
  value: 10
step_len:
  desc: null
  value: 1
valid_setting:
  desc: null
  value: false
wd:
  desc: null
  value: 0.0001
